# Generated by Django 5.1.4 on 2026-02-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chitfund_chittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chittransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
