# Generated by Django 5.1.4 on 2026-02-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chittransaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chittransaction',
            name='chit_fund',
        ),
        migrations.DeleteModel(
            name='ChitFund',
        ),
        migrations.DeleteModel(
            name='ChitTransaction',
        ),
    ]
